development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: appjonny2_db_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: appjonny2_db_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: appjonny2_db_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
