development:
  adapter: postgresql
  encoding: unicode
  database: appjonny_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: appjonny_production
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: appjonny_test
  pool: 5
  username: postgres
  password:
